#!/bin/sh
# /etc/init.d/myapp

case "$1" in
  start)
    echo "Starting My Deleteme App"
    /bin/deleteme
    ;;
  stop)
    echo "Stopping My Deleteme App"
    # Command to stop your application
    ;;
  *)
    echo "Usage: /etc/init.d/myapp {start|stop}"
    exit 1
    ;;
esac

exit 0
